import { Prisma } from "prisma-binding";

const prisma = new Prisma({
  // prisma.graphql is generated by the graphql cli.
  // See the package.json script.
  // It hits your graphql endpoint and creates all
  // the typedefs for all queries, mutations etc.
  // Now we can just call any operation on this prisma
  // instantiation.
  typeDefs: "src/generated/prisma.graphql",
  endpoint: "http://localhost:4466",
  secret: "thisismysupersecrettext",
});

export { prisma as default };
